name: Nightly Publication

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - nightly

jobs:
  publish:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build nightly
        run: ./scripts/build-nightly
      - name: Set up npm
        run: printf "%s\n" email=github-action@dfinity.org always-auth=true >> .npmrc
      - name: Publish
        run: npm publish --tag nightly
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
