name: Nightly Publication

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      # Commit to the nightly branch and push to test.
      - nightly

jobs:
  publish:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build nightly
        run: ./scripts/build-nightly
      - name: Set up npm
        run: printf '%s\n' '//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}' registry=https://registry.npmjs.org/ always-auth=true >> .npmrc
      - name: Publish
        run: npm publish --tag nightly
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
